### GET / 
GET http://localhost:8080

### REGISTER A USER
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username": "admin@x.com",
    "password": "admin1234"
}

### LOGIN A USER
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "admin@x.com",
    "password": "admin1234"
}

### FETCH ALL Todos
GET http://localhost:8080/todos
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgwODMyNzM3LCJleHAiOjE3ODA5MTkxMzd9.B8-7DMhNbdKDnBEprrnzgS9Rje9vL36JMsjabBofKZA"

### CREATE A new todo 
POST http://localhost:8080/todos
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgwODMyNzM3LCJleHAiOjE3ODA5MTkxMzd9.B8-7DMhNbdKDnBEprrnzgS9Rje9vL36JMsjabBofKZA"
Content-Type: application/json

{
    "task" : "will ts work?"
}

### UPDATE a Todo
PUT http://localhost:8080/todos/2
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgwODMyNzM3LCJleHAiOjE3ODA5MTkxMzd9.B8-7DMhNbdKDnBEprrnzgS9Rje9vL36JMsjabBofKZA"
Content-Type: application/json

{
    "completed":1 
}
